#:schema node_modules/wrangler/config-schema.json
name = "test-app"
main = "src/index.ts"
compatibility_date = "2026-02-18"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[vars]
NODE_ENV = "production"

[triggers]
crons = ["* * * * 1"]
